language: python
python: 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_1c3fee7955db_key -iv $encrypted_1c3fee7955db_iv
  -in deploy_rsa.enc -out deploy_rsa -d
install: pip install -r requirements.txt
script: python manage.py test
addons:
  ssh_known_hosts: "$DEPLOY_HOST"
before_deploy:
- openssl aes-256-cbc -K $encrypted_1c3fee7955db_key -iv $encrypted_1c3fee7955db_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo $TRAVIS_BUILD_DIR
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  script: rsync --quiet -rvz $TRAVIS_BUILD_DIR/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIR
  on:
    branch: master
after_deploy:
#- ssh -t $DEPLOY_USER@$DEPLOY_HOST sudo service gunicorn_contacts restart
- ssh -t $DEPLOY_USER@$DEPLOY_HOST  
    "cd $DEPLOY_DIR && 
    docker-compose -f docker-compose-prod.yml build &&
    docker-compose -f docker-compose-prod.yml up -d &&  
    docker rmi \$(docker images | grep '^<none>' | awk '{print $3}')"

#https://oncletom.io/2016/travis-ssh-deploy/
#https://blog.martignoni.net/2019/03/deploy-your-hugo-site/
#https://superuser.com/questions/596900/how-to-enable-sudo-commands-over-ssh-without-asking-password